/* WRITE YOUR PL/SQL QUERY STATEMENT BELOW */

/**
 * 문제 : HTTPS://LEETCODE.COM/PROBLEMS/BIG-COUNTRIES/
 * 레벨 : EASY
 * 결과 : 해결(RUNTIME 439MS FASTER THAN 82.88%, MEMORY 0MB LESS THAN 100.00%)
 */

SELECT NAME, POPULATION, AREA
FROM WORLD
WHERE AREA >= 3000000
OR POPULATION >= 25000000